### ISSUE TITLE
Bug in website

### ISSUE THREAD

**Issue by EinRainerZufall** [SasaKaranovic/OpenFanController#10]
First of all, sorry for all the issues I opened^^

If you switch to PWM mode on the website and then go back to RPM mode, the speed is locked to `OFF`

I'm not that good at programming websites, but in my opinion the mistake is that you query the label as a number and then set it to `OFF` with this IF query without being able to reset it.

https://github.com/SasaKaranovic/OpenFanController/blob/master/Software/Python/webpage/assets/js/kr_gui_fan_status.js#L329,L353

**Comment by SasaKaranovic** [comment]
First of all, no apology needed. You are taking your time to improve this project and help everyone else and I really appreciate that! :)

Seems like you have a reliable way of reproducing this issue. Which is always very helpful and key to fixing them.
Do you mind providing step-by-step actions to reproduce this issue?
Also feel free to add notes for relevant steps, like for example what is the expected behavior vs what is observed behavior.

**Comment by EinRainerZufall** [comment]
The steps are basically as described above:

1. switch to PWM mode on the main page
2. then switch back to RPM mode

Then you will only see "OFF" as the RPM target and you have to reload the website to set a speed

And I would expect that if you move the sliders that the speed changes from "OFF" to a real speed

**Comment by SasaKaranovic** [comment]
I don't know how I missed that typo... thank you for mentioning it!
It should be fixed not.

**Comment by EinRainerZufall** [comment]
ok I have updated my Docker, but the error is still there

**Comment by SasaKaranovic** [comment]
Make sure to clear your cache (ie CTRL+F5) or use a different browser to make sure you are not looking at a cached version.

**Comment by EinRainerZufall** [comment]
The website was still in cache, everything works as it should. Thanks for the fix.
