### ISSUE TITLE
Make better use of HTTP methods

### ISSUE THREAD

**Issue by lord-xeon** [SasaKaranovic/OpenFanController#14]
I'm trying to build a UI around this service and the HTTP server doesn't follow some best practices.

1. Setting fan values is a `GET` that makes changes to something, that should be a `PUT`
2. Making a new profile is a POST, but it uses query string params, ideally, that should be the `payload` of the POST
3. Removing profiles should be a `DELETE` or a `PUT`

**Comment by SasaKaranovic** [comment]
Hey @lord-xeon thanks for the suggestion and taking the time to post it.
Also I would love if you share that UI when it's available. :)

If this was a REST API for purely service-to-service interaction or some other web only interface I would agree.
But in this case I don't necessarily agree that mainly using `GET` is wrong or a bad practice.
Especially if you consider that we want to allow virtually anything to interact with the OpenFAN API.
So if for whatever reason the third-party script/app is unable (or requires some extra work) to send `PUT` request instead of `GET`, it would raise the entry bar for interacting with the API and potentially prevent some users from using it or cause unnecessary "pain points".

But with that said, if using more explicit HTTP methods (ie `PUT`, `DELETE` etc) makes anyone's life easier or removes any road-blocks for future development, we could alias them so both are valid and accepted by the API.
