### ISSUE TITLE
Can you upload CPL file as well?

### ISSUE THREAD

**Issue by astrolemonade** [SasaKaranovic/OpenFanController#16]
Hey!
I tried buying directly from your website but turns out you're not shipping to my country. I tried adding the files to JLCPCB but I am missing the CPL file, tried uploading the same excel to that, it didn't work. I would like to buy it preassembled since I don't have the right tools for the jobs.
![image](https://github.com/SasaKaranovic/OpenFanController/assets/35623921/972fcb77-c940-48cf-84ef-0ba0d6e4315b)
Can you share your input on this, please? Thank you!

**Comment by SasaKaranovic** [comment]
It is already available in the repository ([here](https://github.com/SasaKaranovic/OpenFanController/tree/master/Hardware/Altium_Source_Files/Release/2023-06-04_2321_OpenFan_R03/Pick%20Place)) along all the other files you need to make a board.

You can also buy these from the [shop](https://shop.sasakaranovic.com/products/openfan-pc-fan-controller). They come fully assembled, programmed and with USB-to-motherboard cable.

**Comment by SasaKaranovic** [comment]
> Thank you! You're not shipping to my address, EU country, unfortunately! Buying from you was my very first option! I couldn't contact you to give you additional details since you have restrictions on who can contact you(twitter etc).
> 
> ![image](https://private-user-images.githubusercontent.com/35623921/341730399-899a0858-c7bf-413f-ae4a-f29ee3a635c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODU2MTQsIm5iZiI6MTcxODk4NTMxNCwicGF0aCI6Ii8zNTYyMzkyMS8zNDE3MzAzOTktODk5YTA4NTgtYzdiZi00MTNmLWFlNGEtZjI5ZWUzYTYzNWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE1NTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzE2MjUzZTAyMGVkYjVjZTgwMDMxZmUwMDNiMTJlNjcxZmYyMjY5MjNlNzAzMzdkOTk1Mzk5YjdmN2JjNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rMqNTVJ1hwp79rUX-6r51LP6MjWCjzuvlSWTeHXZcSU)

Please feel free to send an email to shop@sasakaranovic.com
Some locations were disabled by default but there should be no reason why they can't be enabled.
Also my email is on the website and you have obviously reached me through GitHub as well so...

The provided manufacturing package contains all the files you need. Gerbers for the PCB, BOM for sourcing components, pick and place for the assembly and firmware for programming the board.

Without naming any names, some vendors (for some completely arbitrary reason) force their customers to use very specific upload formats and ask for specific column name/order. This is completely arbitrary and they will reject otherwise valid manufacturing package.
I'm sure they might have some internal justification for this, but to me this makes no sense. For example if you send a manufacturing package and it has manufacturer part number as as column number 3 instead of "expected" column number 2, they will reject it instead of allowing you to select which column is which or just parsing the uploaded file...
Also what happens when new vendor X appears and starts forcing users to use different format... then everyone has to produce multiple manufacturing packages for each vendors. This is just not scalable.
I hope you understand where I'm coming from and understand why I don't want to endorse this kind of "behavior".
If you chose/have to work with vendor like this, you can either manually modify the package until they are happy with it, or find a different PCB shop that can accept a standard manufacturing package.

So far people have reported that they have successfully used the provided manufacturing package to order PCBs and PCBAs. On top of that, it's the exact same package that I use for boards on the shop. So there should be no issues.

If your PCB shop is forcing you to have a very specific format, then you can either modify the provided one until they are happy, or find a different vendor that can interpret a standard manufacturing package.

**Comment by SasaKaranovic** [comment]
My point was the opposite, _most_ manufacturers _do use_ a standard manufacturing package. Or they are OK as long as your files contain all the necessary information. If your pick and place file is in imperial instead of metric, they will convert it. If you have manufacturer as column number X, and manufacturer part number as column number Y, they are fine as long as all the information is there.

Unfortunately there are some manufacturers that force some arbitrary format without good reason for it, and that really does not make sense, at least not to me.

Maybe not the best example but imagine if your friend bought a phone online from online store A. And you want to buy exact same one. You go to your favorite online store which happens to be a store B and try to order the exact same phone. But they return an error saying "We have that phone in a different isle than store A. Can you please update your order." Maybe it sounds even more ridiculous in this example but you get the picture...

Is it really different if your manufacturing file says "Buy 20pcs of this Manufacturer Part Number component made by this Manufacturer" or if it says "From Manufacturer X buy 20 pcs of this Manufacturer Part Number component". I think all the information is there but some PCB vendors will say one of those two formats is invalid (for their system).
