### ISSUE TITLE
Questions about lm-sensors, power usage, and firmware modifications of PCB-revisions

### ISSUE THREAD

**Issue by libr3** [SasaKaranovic/OpenFanController#28]
I have become interested in the project and I'm considering whether to purchase a pre-built version, but I have four questions:

1. Does the project work with lm-sensors [1]? If not, I think it would be a good idea to add compatibility since many programs related to controlling fans rely on it, such as fan2go [2], which I particularly like.

2. How many watts can each fan use? One of the products competing with this project would be Corsair devices, which also have official kernel support and work with lm-sensors (like the Corsair Commander Core XT), but Corsair devices only support up to 6 fans, and their firmware is proprietary.

3. I usually compile everything from source (I use Gentoo, a GNU/Linux distribution that, unlike most, is not binary-based): I’ve seen in another issue that you are now sending new revisions of the PCB [3], which have modified firmware because it's adapted to that revision. You mentioned to the user that the only change was adapting it to their hardware revision, but that implies a modification. I'm seriously concerned that when you send me the new revision, I won’t be able to compile from source and install the firmware because the adapted source code for the revision you are sending now is not available in this repository. It would be great if you could publish that modification so anyone—not just me—who has a different revision of the board could modify and reinstall it from source, just as I would do myself. I plan to recompile and reinstall the firmware once I receive the pre-built device, so it would be helpful if you could even release the source code for those revisions to allow me to do so.

4. Do you have an ETA for when you'll release the version with a USB Type-C port? I wouldn't mind paying a bit more for it to have a Type-C port, or finding the cable myself if it has that port and the cable is expensive.

[1] https://github.com/lm-sensors/lm-sensors
[2] https://github.com/markusressel/fan2go
[3] https://github.com/SasaKaranovic/OpenFanController/issues/25#issuecomment-2375801323

**Comment by SasaKaranovic** [comment]
Hey @libr3,

Thanks for the great suggestion. Unfortunately OpenFAN Controller does NOT have lm_sensors integration at the moment.
The maximum current per fans sounds like an easy question to answer but it's not.
Short answer is **by design**, OpenFAN Controller could deliver around 1-1.5A to each fan. Key word being **could**.
However you have to keep in mind that there are many links in the power-supply chain. Depending on your power supply, it would usually supports around ~3-4A (maximum/total) on your SATA power, which then gets divided to however many fans you have. This means that while OpenFAN could easily provide 1A to all 10 fans, your power supply probably can't supply 10A on the SATA power cable, so the limit would be whatever your power supply can **safely** provide.

Also, while I understand what you mean, in my mind I don't think this project is "competing" with anyone/anything. Especially not with products made by billion dollar companies. :)
It's just something that I built for myself and thought others might find useful.
With that said, if you have any doubts or concerns, I would recommend getting a different product that makes you more comfortable.
